### ISSUE TITLE
2.3: Selecting Base Station Type causes crash

### ISSUE THREAD

**Issue by ggee** [DCC-EX/exInstaller#10]
To reproduce, once you start the installer, quickly choose the Base Station Type before arduino-cli finishes.  One observation is that if you wait for the arduino-cli to start before choosing install type, then the exception won't occur.  So it seems that all the selections should be read-only until the arduino-cli is started.

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at BaseStationInstaller.Utils.ArudinoCliHelper.DetectBoard() in F:\TrainStuff\DCC-Ex-Installer\BaseStationInstaller\Utils\ArudinoCliHelper.cs:line 268
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

**Comment by dexslab** [comment]
This has been noticed i need to fix it so that those are disabled immediately

**Comment by dexslab** [comment]
Issue has been fixed on latest dev push
