### ISSUE TITLE
Linux_x64 exinstaller not usable

### ISSUE THREAD

**Issue by dimonic** [DCC-EX/exInstaller#26]
Beta 2.4.0 Linux installer dies when it attempts serial discovery - the Linux executable for serial discovery is not present.
Beta 2.3.1 (latest) Does not even have a Linux executable, and does not have any packages directory.
Beta 2.3.1 (other) is missing a lot of things.
Beta 2.3 Not sure how to use this one at all.

The error messages below are for the Linux_x64 version 2.4.0

**Comment by dimonic** [comment]
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="error getting port list from serial-discovery: starting discovery process: fork/exec /home/dominic/workdir/exInstaller/packages/builtin/tools/serial-discovery/1.2.1/serial-discovery: no such file or directory")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Cc.Arduino.Cli.Commands.V1.ArduinoCoreService.ArduinoCoreServiceClient.BoardList(BoardListRequest request, CallOptions options) in C:\Users\dex35\source\repos\exInstaller\exInstaller\obj\Release\netcoreapp5.0\linux-x64\CommandsGrpc.cs:line 1328
   at Cc.Arduino.Cli.Commands.V1.ArduinoCoreService.ArduinoCoreServiceClient.BoardList(BoardListRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\Users\dex35\source\repos\exInstaller\exInstaller\obj\Release\netcoreapp5.0\linux-x64\CommandsGrpc.cs:line 1318
   at exInstaller.Utils.ArudinoCliHelper.DetectBoard() in C:\Users\dex35\source\repos\exInstaller\exInstaller\Utils\ArudinoCliHelper.cs:line 326
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted

**Comment by dexslab** [comment]
Remove tools folder and packages folder and allow it to redownload proper tools

**Comment by gen2thomas** [comment]
Removing both folders and execute the installer again worked for me. But now only the "/dev/ttyS0" is available as COM port. Which settings are required for the port to be detected by the installer?

**Comment by prchal** [comment]
It helped for me.

**Comment by peteGSX** [comment]
Closing in favour of the new EX-Installer.
