### ISSUE TITLE
Minor issue with upload

### ISSUE THREAD

**Issue by GunflintAndDeadRiverRR** [DCC-EX/exInstaller#4]
I installed to my 'D' drive under the following folder structure:
D:\Data\UserName\Model Railroading\DCC++_Arduino\BaseStationEX\Build\
When I ran the installer it would not upload.
When I moved the installer to:
D:\Data\
It worked.
Just a heads-up in case someone else is as dumb as me and buries the install too deeply in the file structure.
Here's the log output:
Starting ArduinoSketchUploader...
Starting upload process for file 'D:\Data\UserName\Model Railroading\DCC++_Arduino\BaseStationEX\Build\DCCppEX.ino.hex'.
Message: Could not find file 'D:\Data\UserName\Model Railroading\DCC++_Arduino\BaseStationEX\Build\DCCppEX.ino.hex'. 
 StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at ArduinoUploader.ArduinoSketchUploader.UploadSketch()Message: Could not find file 'D:\Data\Sim\Model Railroading\DCC++_Arduino\BaseStationEX\Build\DCCppEX.ino.hex'. 
 StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at ArduinoUploader.ArduinoSketchUploader.UploadSketch()
   at BaseStationInstaller.ViewModels.MainWindowViewModel.CompileSketch()

**Comment by dexslab** [comment]
It looks like you are using the old version please update and try again

**Comment by GunflintAndDeadRiverRR** [comment]
Thanks so much. I'll test again tonight.                                                                                                                                                                                                                                                                                                                                                     From: DexSent: Saturday, July 4, 2020 9:34 AMTo: DCC-EX/BaseStation-InstallerReply To: DCC-EX/BaseStation-InstallerCc: GunflintAndDeadRiverRR; AuthorSubject: Re: [DCC-EX/BaseStation-Installer] Minor issue with upload (#4)
It looks like you are using the old version please update and try again

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DCC-EX/BaseStation-Installer/issues/4#issuecomment-653767084",
"url": "https://github.com/DCC-EX/BaseStation-Installer/issues/4#issuecomment-653767084",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dexslab** [comment]
This issue should be fixed
